RHIDP-431 - [Test automation] Add keycloak plugin test
janus-idp/showcase-e2e pull request #45
Opened 2023-10-18 13:01 UTC by gustavolira

2023-10-18 13:04 UTC, zdrapela commented on README.md
> +q# showcase-e2e
Probably a typo
```suggestion
# showcase-e2e
```

2023-10-18 15:08 UTC, subhashkhileri requested changes

2023-10-18 15:08 UTC, subhashkhileri commented on e2e-test/cypress/e2e/plugins/keycloak/keycloak.ts
> +            const response = await axios.post(
It would be nice to use `cy.request()` instead of `axios`. It will handle all the assertions and logging for you.
instead of you handling and  throwing the error.

2023-10-19 20:21 UTC, gustavolira commented
/retest

2023-10-20 13:16 UTC, gustavolira commented
/retest

2023-10-26 14:09 UTC, subhashkhileri requested changes

2023-10-26 14:09 UTC, subhashkhileri commented on e2e-test/cypress/e2e/plugins/keycloak/catalog-users.spec.ts
> +        expect(UIhelper.verifyDivHasText(`${keycloakUser.firstName} ${keycloakUser.lastName}`));
Since you are already doing assertion in verifyDivHasText(), so expect is not required here as well.

2023-10-26 14:09 UTC, subhashkhileri commented on e2e-test/cypress/support/pageObjects/catalog/catalog-users-obj.ts
> +    static visitUserPage(username) {
This method says visit User Page but its simply getting the element. Would be nice if you can move the `.click();` here.

2023-10-26 14:27 UTC, gustavolira commented on e2e-test/cypress/e2e/plugins/keycloak/catalog-users.spec.ts
> +        loginAsGuest();
@subhashkhileri  Tbh I would not like to use Common.loginAsGuest() because it's doing some verifications like `UIhelper.verifyHeading("Red Hat Developer Hub");` which I don't want here, because most of the cases we are using backstage showcase

2023-10-27 17:43 UTC, josephca submitted a review, later dismissed

2023-10-30 06:54 UTC, subhashkhileri requested changes

2023-10-30 06:54 UTC, subhashkhileri commented on e2e-test/cypress/e2e/plugins/keycloak/catalog-users.spec.ts
> +        loginAsGuest();
@gustavolira Okay, So in that case updating `Common.loginAsGuest();` will make sense? I feel both are doing same thing except the verification. May be we can remove RHDH validation and put something Common verification because all of the test will run for both rhdh and backstage-showcase right?

2023-10-30 06:54 UTC, subhashkhileri commented on e2e-test/cypress/e2e/plugins/keycloak/catalog-users.spec.ts
> +        UIhelper.isHeaderTitleExists('Select a sign-in method').then((isHeaderTitleExists) => {
Now that we are using cy.clearAllCookies(), it will always prompt for login. So I suppose isHeaderTitleExists is no longer necessary.

2023-10-31 21:04 UTC, josephca approved these changes
/lgtm

2023-11-01 15:06 UTC, subhashkhileri commented
/lgtm

2023-11-01 15:07 UTC, josephca commented
@gustavolira Please recommit with ‘-s’.  Thanks!

2023-11-01 17:07 UTC, merged